version: '3.8'

services:
  web:
    build: ./server
    ports: 
      - 9000:9000

    depends_on:
      - postgres_db

    command: >
      sh -c "
      pipenv run python manage.py migrate &&
      pipenv run python manage.py runserver 0.0.0.0:9000
      "

    restart: always

  postgres_db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=fetch_admin
      - POSTGRES_PASSWORD=good-password-postgres
      - POSTGRES_DB=tube_fetch_db
    restart: always
  
volumes: 
  postgres_data: